### ISSUE TITLE
New Module: ThreatMiner

### ISSUE THREAD

**Issue by deadbits** [InQuest/omnibus#20]
**Requires API Key:**
- [ ] Yes
- [x] No

***
**Tasks**
- [x] Write module for IP, Domain, Hash queries
    - Hash will retrieve http traffic
    - IP will retrieve Passive DNS info
    - Domain gets Passive DNS info and Subdomains
- [x] Create child artifacts found by results when applicable
- [x] Test in development branch

**Comment by deadbits** [comment]
Completed in v1.0-prod branch
